def get_platform_capabilities():
    return {
        "facebook": {
            "supports_text": True,
            "supports_images": True,
            "supports_video": True,
            "supports_reels": True,
            "supports_link_posts": True,
            "supports_first_comment": False,
            "requires_title": False,
            "max_media_items": 10,
        },
        "instagram": {
            "supports_text": False,
            "supports_images": True,
            "supports_video": True,
            "supports_reels": True,
            "supports_link_posts": False,
            "supports_first_comment": True,
            "requires_title": False,
            "max_media_items": 10,
        },
        "linkedin": {
            "supports_text": True,
            "supports_images": True,
            "supports_video": True,
            "supports_reels": False,
            "supports_link_posts": True,
            "supports_first_comment": False,
            "requires_title": False,
            "max_media_items": 20,
        },
        "twitter": {
            "supports_text": True,
            "supports_images": True,
            "supports_video": True,
            "supports_reels": False,
            "supports_link_posts": True,
            "supports_first_comment": False,
            "requires_title": False,
            "max_media_items": 4,
        },
        "youtube": {
            "supports_text": False,
            "supports_images": False,
            "supports_video": True,
            "supports_reels": False,
            "supports_link_posts": False,
            "supports_first_comment": False,
            "requires_title": True,
            "max_media_items": 1,
        },
        "blogger": {
            "supports_text": True,
            "supports_images": True,
            "supports_video": True,
            "supports_reels": False,
            "supports_link_posts": True,
            "supports_first_comment": False,
            "requires_title": True,
            "max_media_items": 10,
        },
        "google_business": {
            "supports_text": True,
            "supports_images": True,
            "supports_video": True,
            "supports_reels": False,
            "supports_link_posts": False,
            "supports_first_comment": False,
            "requires_title": False,
            "max_media_items": 1,
        },
        "wordpress": {
            "supports_text": True,
            "supports_images": False,
            "supports_video": False,
            "supports_reels": False,
            "supports_link_posts": True,
            "supports_first_comment": False,
            "requires_title": True,
            "max_media_items": 0,
        },
    }
