services:
  backend:
    build: .
    container_name: socialsync_backend
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    command: sh -c "./wait-for-db.sh && uv run uvicorn app.main:app --host 0.0.0.0 --port 8000"


  worker:
    build: .
    container_name: socialsync_worker
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: uv run celery -A app.worker.celery_app.celery_app worker --loglevel=info -E -Q default


  beat:
    build: .
    container_name: socialsync_beat
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: uv run celery -A app.worker.celery_app.celery_app beat --loglevel=info


  flower:
    build: .
    container_name: socialsync_flower
    env_file: .env
    command: >
      sh -c "
        sleep 15 &&
        uv run celery -A app.worker.celery_app.celery_app --broker=redis://redis:6379/0 flower --port=5555
      "
    ports:
      - "5555:5555"
    depends_on:
      redis:
        condition: service_started
      worker:
        condition: service_started
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:7-alpine
    container_name: socialsync_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: socialsync_redis_ui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  db:
    image: postgres:16-alpine
    container_name: socialsync_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialsync
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: